
def GetVariableType( variable ):
    if ( variable in demographic ):
        return "demographic"
    elif ( variable in treatments ):
        return "treatment"
    elif ( variable in lab_results ):
        return "lab_result"
    elif ( variable in symptoms):
        return "symptoms"
    elif ( variable in comorbidities ):
        return "comorbidity"
    elif ( variable in followup_symptom_list ):
        return "follow_up_symptom"
    elif ( variable in complications ):
        return "complication"
    elif ( variable in others ):
        return "other"
    else:
        print( "Error Unmatched variable" )
        return None
    

demographic=[ 
    'Age au recrutement',
    'Age au recrutement:',
     'BMI:',
    'Electronic cigarettes?',
    'Height in m:',
    'Living where?',
    'Living with?',     
     'Is the participant employed as a Healthcare Worker?  ',
     'Is the participant employed in a Microbiology Laboratory?  ',
    'Patient pregnant?',
     'Sex at birth:',
     'Sexe:',
     'Smoking status:',
    'Weight in kg:'
]
treatments=[
    'Anticoagulants?',
    'Adjunctive therapy during hospitalization',
    'Colchicine?',
    'Dialysis ?',
    'Did or does the patient receive adjunctive therapy?',
    'Did or does the patient receive ventilatory support?',
    'Drugs?',
    'HGO or insulin?',
    'If yes (check all that apply): (choice=Blood transfusion)',
    'If yes (check all that apply): (choice=Dialysis or hemofiltration)',
    'If yes (check all that apply): (choice=Extracorporeal membrane oxygenation (ECMO))',
    'If yes (check all that apply): (choice=High-frequency oscillatory ventilation (HFOV))',
    'If yes (check all that apply): (choice=Inhaled nitric oxide (iNO))',
    'If yes (check all that apply): (choice=Invasive support with mechanical ventilation)',
    'If yes (check all that apply): (choice=Neuromuscular blocking agents)',
    'If yes (check all that apply): (choice=Non-invasive cannula/mask support)',
    'If yes (check all that apply): (choice=Non-invasive support via High-flow nasal cannula (HFNC))',
    'If yes (check all that apply): (choice=Non-invasive ventilation CPAP/BPAP)',
    'If yes (check all that apply): (choice=Other(s), specify)',
    'If yes (check all that apply): (choice=Prone positioning)',
    'If yes (check all that apply): (choice=Tracheostomy)',
    'If yes (check all that apply): (choice=Vasopressor/inotropic support)',
    'If yes: (choice=Blood transfusion)',
    'If yes: (choice=Dialysis or hemofiltration)',
    'If yes: (choice=Extracorporeal membrane oxygenation (ECMO))',
    'If yes: (choice=High-flow nasal cannula (HFNC))',
    'If yes: (choice=High-frequency oscillatory ventilation)',
    'If yes: (choice=Inhaled nitric oxide (iNO))',
    'If yes: (choice=Invasive with mechanical ventilation)',
    'If yes: (choice=Neuromuscular blocking agents)',
    'If yes: (choice=Non-invasive ventilation CPAP/BPAP)',
    'If yes: (choice=Other(s), (specify))',
    'If yes: (choice=Oxygen therapy with cannula/mask)',
    'If yes: (choice=Prone positioning)',
    'If yes: (choice=Tracheostomy)',
    'If yes: (choice=Vasopressor/inotropic support)',
    'On arrival,  is the participant receiving oxygen ?',
    'Oxygen therapy',
    'Please specify drugs used. (choice=Amphetamines)',
    'Please specify drugs used. (choice=Cannabis)',
    'Please specify drugs used. (choice=Cocaine)',
    'Please specify drugs used. (choice=Opiods)',
    'Please specify drugs used. (choice=Other)',
    'Systemic corticosteroid?',
    'Treatments administered: (choice=Antifungal)',
    'Treatments administered: (choice=Azithromycin (Zithromax))',
    'Treatments administered: (choice=Colchicine)',
    'Treatments administered: (choice=Hydroxychloroquine (Plaquenil))',
    'Treatments administered: (choice=IVIG)',
    'Treatments administered: (choice=Interferon alpha)',
    'Treatments administered: (choice=Interferon beta)',
    'Treatments administered: (choice=Ivermectin (Stromectol))',
    'Treatments administered: (choice=Kineret (Anakinra))',
    'Treatments administered: (choice=Lopinavir/Ritonavir (Kaletra))',
    'Treatments administered: (choice=Neuraminidase inhibitor)',
    'Treatments administered: (choice=Other COVID-19 treatments (specify))',
    'Treatments administered: (choice=Other antibiotic (specify))',
    'Treatments administered: (choice=Other antiviral (specify))',
    'Treatments administered: (choice=Other immunomodulator (specify))',
    'Treatments administered: (choice=Plasma)',
    'Treatments administered: (choice=Remdesivir)',
    'Treatments administered: (choice=Ribavirin)',
    'Treatments administered: (choice=Sarilumab (Kevzara))',
    'Treatments administered: (choice=Stem cells)',
    'Treatments administered: (choice=Systematic corticosteroid)',
    'Treatments administered: (choice=Tocilizumab (Actemra))',
    'Ventilatory support:'
]
lab_results=[
    'Albumin (LOWEST value)',
    'Albumin:',
    'At the time of collection, FiO2:',
    'At the time of collection, SpO2 on oxygen:',
    'At the time of collection, is the participant receiving oxygen ?',
    'ACE inhibitor or Angiotensin Receptor Blocker?',
    'ALT (HIGHEST value)',
    'ALT:',
    'APTT (activated partial thromboplastin time) (HIGHEST value)',
    'APTT (activated partial thromboplastin time):',
    'AVPU Scale:',
    'Baseline creatinine:',
    'Basophil (relative value) (HIGHEST value)',
    'Basophil (relative value):',
    'Basophil (x 10^9/L):',
    'C-reactive protein (CRP) (HIGHEST value)',
    'C-reactive protein (CRP):',
    'Creatinine (HIGHEST value)',
    'Creatinine:',
    'D-Dimer (HIGHEST value)',
    'D-Dimer:',
    'Diastolic BP:',
    'Diastolic BP:.1',
    'Eosinophil (relative value)',
    'Eosinophil (relative value) (HIGHEST value)',
    'Eosinophil (x 10^9/L):',
    'FiO2 (associated with the previous SpO2):',
    'Glasgow Coma Scale (GCS) - lowest value:',
    'Glucose (HIGHEST value)',
    'Glucose:',
    'Haemoglobin (LOWEST value)',
    'Haemoglobin :',
    'Heart rate (associated with BP above):',
    'Heart rate (associated with BP above):.1',
    'Immunosupressed state?',
    'International Normalized Ratio (INR) (HIGHEST value)',
    'International Normalized Ratio (INR):',
    'LDH (HIGHEST value)',
    'LDH:',    
    'Lymphocyte (relative value) (LOWEST value)',
    'Lymphocyte (relative value):',
    'Lymphocyte (x 10^9/L):',
    'Monocyte (relative valeur) (HIGHEST value)',
    'Monocyte (relative value):',
    'Monocyte (x 10^9/L):',
    'Neutrophil (relative value) (HIGHEST value)',
    'Neutrophil (x 10^9/L):',
    'Neutrophils (relative value):',
    'O2 saturation at room air :',
    'O2 saturation at room air :.1',
    'On arrival, SpO2 on oxygen:',
    'Platelet (LOWEST value)',
    'Platelets:',
    'Positive bacterial culture documented during hospitalization?',
    'Positive viral infection documented during hospitalization:',
    'Potassium K+ (HIGHEST value)',
    'Potassium K+:',
    'Procalcitonin (PCT):',
    'Respiratory rate (associated with BP above):',
    'Respiratory rate (associated with BP above):.1',
    'Sodium Na+ (HIGHEST value)',
    'Sodium Na+:',
    'SpO2 (the lowest associated with the highest support):',
    'Systolic BP:',
    'Systolic BP:.1',
    'Temperature:',
    'Temperature:.1',
    'Total Bilirubin:',
    'Total WBC count (HIGHEST value) ',
    'Total WBC count:',
    'Total bilirubin (HIGHEST value)',
    'Urea (HIGHEST value)',
    'Urea:'
]
symptoms=[
    'Asymptomatic?',
    'Joint pain (Arthralgia) ?',
    'Confusion / altered mental status ?',
    'Red eye (Conjunctivitis) ?',
    'Seizure ?',
    'Diarrhea ?',
    'Abdominal pain ?',
    'Chest pain ?',
    'Shortness of breath (Dyspnea) ?',
    'Dizziness ?',
    'Extremity weakness or numbness ?',
    'Fatigue ?',
    'Fever (?38.0 Celcius) ?',
    'Hemoptysis / Bloody sputum ?',
    'Loss of appetite ?',
    'Ear pain ?',
    'Sore throat ?',
    'Headache ?',
    'Muscle aches (Myalgia) ?',
    'Nausea / vomiting ?',
    'Leg swelling (Edema) ?',
    'Loss of taste / lost of smell ?',
    'Skin rash ?',
    'Runny nose (Rhinorrhea) ?',
    'Wheezing or stridor ?',
    'Cough ?',
    'Trouble speaking (Aphasia / Dysphasia) ?'
]
followup_symptom_list=[
    'Joint pain (Arthralgia) ?.1',
    'Confusion / altered mental status ?.1',
    'Red eye (Conjunctivitis) ?.1',
    'Seizure ?.1',
    'Diarrhea ?.1',
    'Abdominal pain ?.1',
    'Chest pain ?.1',
    'Shortness of breath (Dyspnea) ?.1',
    'Dizziness ?.1',
    'Extremity weakness or numbness ?.1',
    'Fatigue ?.1',
    'Fever (?38.0 Celcius) ?.1',
    'Hemoptysis / Bloody sputum ?.1',
    'Loss of appetite ?.1',
    'Ear pain ?.1',
    'Sore throat ?.1',
    'Headache ?.1',
    'Muscle aches (Myalgia) ?.1',
    'Nausea / vomiting ?.1',
    'Leg swelling (Edema) ?.1',
    'Loss of taste / lost of smell ?.1',
    'Skin rash ?.1',
    'Runny nose (Rhinorrhea) ?.1',
    'Wheezing or stridor ?.1',
    'Cough ?.1',
    'Trouble speaking (Aphasia / Dysphasia) ?.1'
]
comorbidities=[
    'Prior transient ischemic attack (TIA) ?',
    'Asthma ?',
    'Other chronic cardiac disease ?',
    'Other chronic neurological disorder (other than stroke/TIA) ?',
    'Other chronic lung disease ? ',
    'Prior stroke ? ',
    'Malignant neoplasm ?',
    'Dementia ? ',
    'Diabetes ?',
    'Atrial fibrillation or flutter ?',
    'HIV or AIDS ?',
    'Arterial Hypertension ?',
    'Pulmonary hypertension ?',
    'Immunosupressed state?',
    'Prior myocardial infarction ?',
    'Heart failure ?',
    'Coronary artery disease ?',
    'Chronic hematologic disease ?',
    'Liver disease ?',
    'Malnutrition ?',
    'COPD (emphysema, chronic bronchitis) ?',
    'Obesity ?',
    'Psychiatric disease?',
    'Chronic kidney disease ?',
    'Rheumatologic disease ?',
    'Does the patient have other comorbidities?',
    'Anxiety and depression:',
    'Breathlessness:',
    'Coronary angiography (Cardiac catheterization)?',
    'Endocarditis? ',
    'Malignant neoplasm - actively receiving treatment?',
    'Malignant neoplasm - metastatic?',
    'Non-ST-elevation myocardial infarction (NSTEMI)? ',
    'Number of comorbidities: ',
    'Number of other comorbidities: ',
    'Number of other complications: ',
    'Other immunosuppressive medications?',
    'Has the participant had any new disease and/or worsening and/or deterioration of a pre-existing disease?',
    'Severity of COPD:'
]
complications=[
    "TIA?",
    "Anemia?",
    "Cardiac arrest?",
    "Other cardiac arrhythmia?",
    "Stroke?",
    "Bacteremia?",
    "Bronchiolitis?",
    "Seizure?",
    "Liver dysfunction?",
    "Pulmonary embolism (PE)?",
    "Endocarditis?",
    "Pleural effusion?",
    "New atrial fibrillation or flutter (AF)?",
    "Ventricular tachycardia or fibrillation (VT/VF)?",
    "Left ventricular function?",
    "Gastrointestinal haemorrhage?",
    "Hyperglycemia?",
    "Hypoglycemia?",
    "Decompensated heart failure?",
    "Acute kidney injury?",
    "Non-ST-elevation myocardial infarction (NSTEMI)?",
    "ST-elevation myocardial infarction (STEMI)?",
    "Meningitis or encephalitis?",
    "Myocarditis?",
    "Pancreatitis?",
    "Pericarditis?",
    "Bacterial pneumonia?",
    "Cryptogenic organizing pneumonia (COP)?",
    "Viral pneumonia/pneumonitis?",
    "Pneumothorax?",
    "Rhabdomyolysis or myositis?",
    "Acute Respiratory Distress Syndrome (ARDS)?",
    "If yes, specify severity:  (Adult Berlin scale; ticked not documented for children because PALICC scale) :",
    "Deep vein thrombosis (DVT)?",
    "Disseminated intravascular coagulation (DIC)?",
    "Other complications?",
    "Positive viral infection documented during hospitalization:",
    "Positive bacterial culture documented during hospitalization?"
]
others=[
    'Ability to self-care at discharge versus pre-COVID:',
    'Disposition:',
    'Does the participant report persistent symptoms related to SARS-CoV-2 infection?',
    'Duration of hospitalization:',
    'Emergency visit only?',
    'How many times have you fallen in the past year?',
    'How much difficulty do you have climbing a flight of 10 stairs?',
    'How much difficulty do you have lifting or carrying 10 lbs?',
    'How much difficulty do you have transferring from a chair to a bed?',
    'How much difficulty do you have walking across a room?',
    'How would you rate your current level of functioning? See options above.',
    'ICU admission?',
    'If a screening test for SARS-CoV-2 by PCR was performed, what is the most severe severity level (according to WHO) achieved?',
    'If yes, specify virus: (choice=Adenovirus)',
    'If yes, specify virus: (choice=Influenza)',
    'If yes, specify virus: (choice=Metapneumovirus)',
    'If yes, specify virus: (choice=Other, specify)',
    'If yes, specify virus: (choice=Parainfluenza)',
    'If yes, specify virus: (choice=RSV)',
    'If yes, specify virus: (choice=Rhinovirus/enterovirus)',
    'Level of care (final):',
    'Long Covid',
    'Mobility',
    'Pain and discomfort:',
    'Self-care',
    'Usual activities, including work, study, housework, family or leisure activities:',
    'Vital status at discharge:',
    'Vital status:'
]
