from GeneticAlgorithmLauncher import SimplifyNetworkNames
import pickle

def MakeMapping():
    mapping = dict( zip( variables, simple_mapping ) )
    return mapping

def MakeReverseMapping():
    mapping = dict( zip( simple_mapping, variables ) )
    return mapping
    
def MakeMappingFile( filename ):
    mapping_file = open( filename, 'ab' )
    mapping = dict( zip( variables, simple_mapping ) )
    pickle.dump( mapping, mapping_file )
    mapping_file.close()

variables = [
    'ACE inhibitor or Angiotensin Receptor Blocker?',
    'If a screening test for SARS-CoV-2 by PCR was performed, what is the most severe severity level (according to WHO) achieved?',
    'ALT (HIGHEST value)',
    'Coronary angiography (Cardiac catheterization)?',
    'ALT:',
    'APTT (activated partial thromboplastin time):',
    'Meningitis or encephalitis?',
    'AVPU Scale:',
    'Temperature:.1',
    'Treatments administered: (choice=Ribavirin)',
    'Abdominal pain ?',
    'Haemoglobin (LOWEST value)',
    'Trouble speaking (Aphasia / Dysphasia) ?',
    'Abdominal pain ?.1',
    'Acute Respiratory Distress Syndrome (ARDS)?',
    'Psychiatric disease?',
    'Acute kidney injury?',
    'Baseline creatinine:',
    'Cardiac arrest?',
    'Dizziness ?',
    'Adjunctive therapy during hospitalization',
    'Breathlessness:',
    'Treatments administered: (choice=Lopinavir/Ritonavir (Kaletra))',
    'Age au recrutement:',
    'If yes, specify virus: (choice=RSV)',
    'Albumin (LOWEST value)',
    'Albumin:',
    'Anxiety and depression:',
    'Vital status at discharge:',
    'Arterial Hypertension ?',
    'Asymptomatic?',
    'Immunosupressed state?',
    'Obesity ?',
    'At the time of collection, SpO2 on oxygen:',
    'APTT (activated partial thromboplastin time) (HIGHEST value)',
    'How much difficulty do you have climbing a flight of 10 stairs?',
    'At the time of collection, is the participant receiving oxygen ?',
    'Duration of hospitalization:',
    'BMI:',
    'Bacteremia?',
    'Total WBC count (HIGHEST value) ',
    'Bacterial pneumonia?',
    'New atrial fibrillation or flutter (AF)?',
    'Basophil (relative value) (HIGHEST value)',
    'Treatments administered: (choice=Stem cells)',
    'Basophil (relative value):',
    'Basophil (x 10^9/L):',
    'Electronic cigarettes?',
    'FiO2 (associated with the previous SpO2):',
    'HGO or insulin?',
    'Bronchiolitis?',
    'Ear pain ?.1',
    'C-reactive protein (CRP):',
    'C-reactive protein (CRP) (HIGHEST value)',
    'COPD (emphysema, chronic bronchitis) ?',
    'Potassium K+ (HIGHEST value)',
    'Smoking status:',
    'Chest pain ?',
    'Did or does the patient receive adjunctive therapy?',
    'Other chronic cardiac disease ?',
    'Sore throat ?.1',
    'Total Bilirubin:',
    'Chronic hematologic disease ?',
    'Glucose (HIGHEST value)',
    'Leg swelling (Edema) ?.1',
    'Urea:',
    'Chronic kidney disease ?',
    'Confusion / altered mental status ?',
    'If yes (check all that apply): (choice=Invasive support with mechanical ventilation)',
    'If yes, specify virus: (choice=Rhinovirus/enterovirus)',
    'Treatments administered: (choice=Systematic corticosteroid)',
    'Confusion / altered mental status ?.1',
    'Coronary artery disease ?',
    'If yes: (choice=High-flow nasal cannula (HFNC))',
    'Please specify drugs used. (choice=Amphetamines)',
    'Cough ?.1',
    'If yes (check all that apply): (choice=Tracheostomy)',
    'Cryptogenic organizing pneumonia (COP)?',
    'Positive bacterial culture documented during hospitalization?',
    'D-Dimer (HIGHEST value)',
    'Diarrhea ?.1',
    'D-Dimer:',
    'Decompensated heart failure?',
    'Headache ?.1',
    'On arrival, SpO2 on oxygen:',
    'Treatments administered: (choice=Interferon alpha)',
    'Deep vein thrombosis (DVT)?',
    'If yes (check all that apply): (choice=Other(s), specify)',
    'Patient pregnant?',
    'Dementia ? ',
    'Diastolic BP:',
    'Diastolic BP:.1',
    'Treatments administered: (choice=Interferon beta)',
    'Did or does the patient receive ventilatory support?',
    'Muscle aches (Myalgia) ?',
    'Pain and discomfort:',
    'Disposition:',
    'Malignant neoplasm ?',
    'Sodium Na+:',
    'Dizziness ?.1',
    'Does the participant report persistent symptoms related to SARS-CoV-2 infection?',
    'Treatments administered: (choice=Colchicine)',
    'Does the patient have other comorbidities?',
    'If yes: (choice=Other(s), (specify))',
    'Drugs?',
    'Atrial fibrillation or flutter ?',
    'If yes: (choice=Prone positioning)',
    'Ear pain ?',
    'Is the participant employed as a Healthcare Worker?  ',
    'Neutrophils (relative value):',
    'Seizure ?',
    'Headache ?',
    'If yes (check all that apply): (choice=Prone positioning)',
    'Emergency visit only?',
    'If yes: (choice=Vasopressor/inotropic support)',
    'Endocarditis? ',
    'Eosinophil (relative value)',
    'Eosinophil (relative value) (HIGHEST value)',
    'Eosinophil (x 10^9/L):',
    'Please specify drugs used. (choice=Cocaine)',
    'Extremity weakness or numbness ?.1',
    'Treatments administered: (choice=Other COVID-19 treatments (specify))',
    'Fatigue ?',
    'Glasgow Coma Scale (GCS) - lowest value:',
    'Fever (?38.0 Celcius) ?.1',
    'If yes, specify virus: (choice=Metapneumovirus)',
    'Cough ?',
    'Respiratory rate (associated with BP above):.1',
    'Gastrointestinal haemorrhage?',
    'Liver dysfunction?',
    'Platelets:',
    'Treatments administered: (choice=Other antibiotic (specify))',
    'Glucose:',
    'Sodium Na+ (HIGHEST value)',
    'HIV or AIDS ?',
    'How many times have you fallen in the past year?',
    'Haemoglobin :',
    'Pancreatitis?',
    'Has the participant had any new disease and/or worsening and/or deterioration of a pre-existing disease?',
    'ST-elevation myocardial infarction (STEMI)?',
    'Non-ST-elevation myocardial infarction (NSTEMI)? ',
    'Please specify drugs used. (choice=Other)',
    'Heart failure ?',
    'Pericarditis?',
    'Heart rate (associated with BP above):',
    'Treatments administered: (choice=Neuraminidase inhibitor)',
    'Heart rate (associated with BP above):.1',
    'LDH:',
    'Living with?',
    'Rhabdomyolysis or myositis?',
    'Height in m:',
    'Creatinine:',
    'Hemoptysis / Bloody sputum ?',
    'Hemoptysis / Bloody sputum ?.1',
    'How much difficulty do you have walking across a room?',
    'Seizure?',
    'How much difficulty do you have lifting or carrying 10 lbs?',
    'Loss of taste / lost of smell ?.1',
    'How much difficulty do you have transferring from a chair to a bed?',
    'Lymphocyte (relative value) (LOWEST value)',
    'Runny nose (Rhinorrhea) ?.1',
    'Myocarditis?',
    'How would you rate your current level of functioning? See options above.',
    'Hyperglycemia?',
    'Hypoglycemia?',
    'International Normalized Ratio (INR):',
    'ICU admission?',
    'On arrival,  is the participant receiving oxygen ?',
    'Urea (HIGHEST value)',
    'If yes (check all that apply): (choice=Extracorporeal membrane oxygenation (ECMO))',
    'If yes (check all that apply): (choice=High-frequency oscillatory ventilation (HFOV))',
    'If yes (check all that apply): (choice=Inhaled nitric oxide (iNO))',
    'If yes (check all that apply): (choice=Non-invasive support via High-flow nasal cannula (HFNC))',
    'Red eye (Conjunctivitis) ?.1',
    'If yes (check all that apply): (choice=Neuromuscular blocking agents)',
    'International Normalized Ratio (INR) (HIGHEST value)',
    'If yes (check all that apply): (choice=Non-invasive cannula/mask support)',
    'If yes: (choice=Inhaled nitric oxide (iNO))',
    'Seizure ?.1',
    'If yes (check all that apply): (choice=Non-invasive ventilation CPAP/BPAP)',
    'If yes, specify virus: (choice=Influenza)',
    'Other chronic neurological disorder (other than stroke/TIA) ?',
    'Platelet (LOWEST value)',
    'Positive viral infection documented during hospitalization:',
    'Procalcitonin (PCT):',
    'Sexe:',
    'If yes (check all that apply): (choice=Vasopressor/inotropic support)',
    'Liver disease ?',
    'If yes, specify virus: (choice=Adenovirus)',
    'Total WBC count:',
    'If yes, specify virus: (choice=Other, specify)',
    'If yes, specify virus: (choice=Parainfluenza)',
    'Ventilatory support:',
    'Pneumothorax?',
    'Pulmonary hypertension ?',
    'Treatments administered: (choice=Antifungal)',
    'If yes: (choice=Dialysis or hemofiltration)',
    'Muscle aches (Myalgia) ?.1',
    'If yes: (choice=Extracorporeal membrane oxygenation (ECMO))',
    'Other immunosuppressive medications?',
    'LDH (HIGHEST value)',
    'Trouble speaking (Aphasia / Dysphasia) ?.1',
    'Viral pneumonia/pneumonitis?',
    'If yes: (choice=Invasive with mechanical ventilation)',
    'If yes: (choice=Non-invasive ventilation CPAP/BPAP)',
    'Treatments administered: (choice=Sarilumab (Kevzara))',
    'Treatments administered: (choice=Remdesivir)',
    'If yes: (choice=Oxygen therapy with cannula/mask)',
    'If yes: (choice=Tracheostomy)',
    'Diabetes ?',
    'If yes: (choice=Neuromuscular blocking agents)',
    'Neutrophil (relative value) (HIGHEST value)',
    'Prior stroke ? ',
    'Systemic corticosteroid?',
    'Joint pain (Arthralgia) ?',
    'Joint pain (Arthralgia) ?.1',
    'Leg swelling (Edema) ?',
    'Systolic BP:',
    'Level of care (final):',
    'If yes (check all that apply): (choice=Blood transfusion)',
    'Living where?',
    'Potassium K+:',
    'Loss of appetite ?',
    'Loss of taste / lost of smell ?',
    'Wheezing or stridor ?.1',
    'Lymphocyte (relative value):',
    'Lymphocyte (x 10^9/L):',
    'Rheumatologic disease ?',
    'Malnutrition ?',
    'Other chronic lung disease ? ',
    'Mobility',
    'Monocyte (relative valeur) (HIGHEST value)',
    'O2 saturation at room air :.1',
    'Monocyte (relative value):',
    'Prior transient ischemic attack (TIA) ?',
    'Monocyte (x 10^9/L):',
    'Treatments administered: (choice=IVIG)',
    'Nausea / vomiting ?',
    'Sex at birth:',
    'Temperature:',
    'If yes: (choice=Blood transfusion)',
    'Number of other complications: ',
    'O2 saturation at room air :',
    'Treatments administered: (choice=Plasma)',
    'Other cardiac arrhythmia?',
    'Pleural effusion?',
    'Shortness of breath (Dyspnea) ?.1',
    'Extremity weakness or numbness ?',
    'Disseminated intravascular coagulation (DIC)?',
    'Sore throat ?',
    'TIA?',
    'Self-care',
    'If yes: (choice=High-frequency oscillatory ventilation)',
    'Treatments administered: (choice=Kineret (Anakinra))',
    'Please specify drugs used. (choice=Cannabis)',
    'Please specify drugs used. (choice=Opiods)',
    'Treatments administered: (choice=Ivermectin (Stromectol))',
    'At the time of collection, FiO2:',
    'Ventricular tachycardia or fibrillation (VT/VF)?',
    'Oxygen therapy',
    'Treatments administered: (choice=Other immunomodulator (specify))',
    'Usual activities, including work, study, housework, family or leisure activities:',
    'Respiratory rate (associated with BP above):',
    'Treatments administered: (choice=Hydroxychloroquine (Plaquenil))',
    'Runny nose (Rhinorrhea) ?',
    'If yes (check all that apply): (choice=Dialysis or hemofiltration)',
    'Systolic BP:.1',
    'Total bilirubin (HIGHEST value)',
    'Nausea / vomiting ?.1',
    'Weight in kg:',
    'Ability to self-care at discharge versus pre-COVID:',
    'SpO2 (the lowest associated with the highest support):',
    'Skin rash ?',
    'Creatinine (HIGHEST value)',
    'Number of other comorbidities: ',
    'Treatments administered: (choice=Other antiviral (specify))',
    'Stroke?',
    'Neutrophil (x 10^9/L):',
    'Wheezing or stridor ?',
    'Vital status:',
    'Anemia?',
    'Fever (?38.0 Celcius) ?',
    'Treatments administered: (choice=Tocilizumab (Actemra))',
    'Red eye (Conjunctivitis) ?',
    'Asthma ?',
    'Treatments administered: (choice=Azithromycin (Zithromax))',
    'Colchicine?',
    'Long Covid',
    'Age au recrutement',
    'Dialysis ?',
    'Prior myocardial infarction ?',
    'Number of comorbidities: ',
    'Diarrhea ?',
    'Shortness of breath (Dyspnea) ?',
    'Malignant neoplasm - metastatic?',
    'Malignant neoplasm - actively receiving treatment?',
    'Is the participant employed in a Microbiology Laboratory?  ',
    'Anticoagulants?',
    'Severity of COPD:',
    'Sex at birth'
]

simple_mapping = [
    'ACE Inh',
    'SEV',
    'ALT H',
    'Cor Ang',
    'ALT',
    'APTT',
    'Mening',
    'AVPU Sc',
    'Temp.1',
    'T Ribav',
    'Ab Pain',
    'Haemogl L',
    'Aphasia',
    'Ab Pain.1',
    'ARDS',
    'Psych Dis',
    'Kidney Inj',
    'Base. Creat',
    'Card Arr',
    'Dizzy',
    'Adj Tpy Hos',
    'Breathless:',
    'T Kaletra',
    'Age',
    'V RSV',
    'Albumin L',
    'Albumin',
    'Anxiety/D.',
    'Vital Dis',
    'Art. Hyper.',
    'Asympt.',
    'Immunosupr',
    'Obesity',
    'Coll SpO2',
    'APTT H',
    'Dif Stairs',
    'Rec O',
    'Hos Dur',
    'BMI',
    'Bacterem',
    'Tot WBC H',
    'Bact Pneum',
    'New Atr Fibr',
    'Baso R H',
    'T Stem Cs',
    'Baso R',
    'Baso u',
    'Ele Cig',
    'FiO2->SPO2',
    'HGO/Ins',
    'Bronch',
    'Ear P.1',
    'CRP',
    'CRP H',
    'COPD',
    'K+ H',
    'Smoke',
    'Chest P',
    'Adj Tpy',
    'Chr Card Dis',
    'Sore Throat.1',
    'Tot Bili',
    'Chr Hema Dis',
    'Glucose H',
    'Edema.1',
    'Urea',
    'Chr Kidn Dis',
    'Confusion',
    'Inv Mech Vent',
    'V Rhinov/Enterov',
    'T Sys Cortic',
    'Confusion.1',
    'Cor Art Dis',
    'HFNC',
    'D Amphet',
    'Cough.1',
    'Trach Hos',
    'COP',
    'Pos Bact',
    'D-Dimer H',
    'Diarrhea.1',
    'D-Dimer',
    'Decomp Heart F',
    'Headache.1',
    'Arr SpO2->O',
    'T Interf Alpha',
    'DVT',
    'Oth Adj Tpy Hos',
    'Pregn',
    'Dementia',
    'Diastolic BP',
    'Diastolic BP.1',
    'T Interf Beta',
    'Rec Vent Sup?',
    'Myalgia',
    'Pain',
    'Disp',
    'Malign Neop',
    'Na+',
    'Dizzy.1',
    'Pers Symp Cov',
    'T Colchicine',
    'Oth Comorb',
    'Oth Adj Tpy',
    'Drugs',
    'Atr Fibr',
    'Prone Pos',
    'Ear Pain',
    'Health Work',
    'Neutrop R',
    'Seizure',
    'Headache',
    'Prone Pos Hos',
    'Emerg Vis Only',
    'Vasopr/Inotr Sup',
    'Endocard',
    'Eosinop R',
    'Eosinop R H',
    'Eosinop u',
    'Dr Cocaine',
    'Extrem Weak.1',
    'T Other',
    'Fatigue',
    'GCS L',
    'Fever.1',
    'V Metapneumovs',
    'Cough',
    'Resp Rate BP.1',
    'Gastroint Haem',
    'Liv Dysf',
    'Platelets',
    'T Oth Antib',
    'Glucose',
    'Na+ H',
    'HIV/AIDS',
    'Fall Past Y',
    'Haemoglob',
    'Pancreat',
    'New/Worse Dis',
    'STEMI',
    'NSTEMI',
    'Drug Oth',
    'Heart Fail',
    'Pericard',
    'Heart Rate BP',
    'T Neuram Inhib',
    'Heart Rate, BP.1',
    'LDH',
    'Living With',
    'Rhabdom',
    'Height',
    'Creatinine',
    'Hemoptysis/B',
    'Hemoptysis/B.1',
    'Dif Walk',
    'Seiz',
    'Dif Lift',
    'Taste/Smell.1',
    'Dif Chair->Bed',
    'Lymph R L',
    'Rhin.1',
    'Myocard',
    'Cur Func',
    'Hyperglyc',
    'Hypoglyc',
    'INR',
    'ICU Adm',
    'Arr Rec O',
    'Urea H',
    'ECMO',
    'HFOV',
    'iNO',
    'HFNC',
    'Conjunct.1',
    'Neurom Bs Hos',
    'INR H',
    'Non-I C/M Hos',
    'iNO',
    'Seiz.1',
    'CPAP/BPAP Hos',
    'V Inf',
    'Oth Chron Neuro D',
    'Platelet L',
    'Pos Viral Hos',
    'PCT',
    'Sexe',
    'Vasopr/Inotr Sup Hos',
    'Liv Dis',
    'V Adenov',
    'Tot WBC C',
    'V Oth',
    'V Parainfl',
    'Vent Sup',
    'Pneumoth',
    'Pulm Hyper',
    'T Antifung',
    'Dial or Hemof',
    'Myalgia.1',
    'ECMO',
    'Oth Immunos med',
    'LDH H',
    'Aph/Dysph.1',
    'Vir pneum',
    'Inv-Mech Vent',
    'CPAP/BPAP',
    'T Kevzara',
    'T Remdes',
    'O Tpy A/M',
    'Trach',
    'Diabetes',
    'Neurom Bs',
    'Neutrop R H',
    'Pr Stroke',
    'Sys Cortic',
    'Arthralgia',
    'Arthralgia.1',
    'Edema',
    'Syst BP',
    'Care(Final)',
    'Blood Transf Hos',
    'Living Where',
    'K+',
    'Loss of Appetite',
    'Taste/Smell',
    'Wheeze/Strid.1',
    'Lymph R',
    'Lymph u',
    'Rheumat Dis',
    'Malnutr',
    'Oth Chr Lung Dis',
    'Mobil',
    'Monoc R H',
    'O2 Sat Room.1',
    'Monoc R',
    'Pr TIA',
    'Monoc u',
    'T IVIG',
    'Nausea',
    'Sex Birth',
    'Temp',
    'Blood Transf',
    'Oth Comp C',
    'O2 Sat Room',
    'T Plasma',
    'Oth Card Arrh',
    'Pleural Eff',
    'Dyspnea.1',
    'Extrem Weak',
    'DIC',
    'Sore Throat',
    'TIA',
    'Self-care',
    'H-freq Osc Vent.',
    'T Anakinra',
    'Dr Cannabis',
    'Dr Opiods',
    'T Strom',
    'Coll FiO2',
    'VT/VF',
    'O Tpy',
    'T Oth Immunomod',
    'Usual Activ',
    'Resp Rate BP',
    'T Plaquen',
    'Rhinorrhea',
    'Dial or Hemof Hos',
    'Syst BP.1',
    'Tot Bili H',
    'Nausea.1',
    'Weight',
    'Self-care->Disc',
    'SpO2 L->H Sup',
    'Skin Rash',
    'Creatinine H',
    'Oth Comorb C',
    'T Oth Antiv',
    'Stroke',
    'Neutrop u',
    'Wheeze/Strid',
    'Vital',
    'Anemia',
    'Fever',
    'T Actemra',
    'Conjunct',
    'Asthma',
    'T Zithromax',
    'Colchicine?',
    'Long Covid',
    'Age',
    'Dialysis',
    'Pr Myoc Inf',
    'Comorb C',
    'Diarrhea',
    'Dyspnea',
    'Malign Neop Meta',
    'Malign Neop Treat',
    'Microb Work',
    'Anticoag',
    'Sev COPD',
    'Sex'
]


def AddToMappingLongCov( dictionary_file, to_filename ):
    dbfile = open(dictionary_file, 'rb')     
    mapping = pickle.load(dbfile)
    for i in range( len( long_cov_missing ) ):
        mapping[ long_cov_missing[ i ] ] = long_cov_mapping[ i ]
    dbfile.close()
    file = open( to_filename, "ab" )
    pickle.dump( mapping, file )
    file.close()

def AddToMappingSev( dictionary_file, to_filename ):
    dbfile = open(dictionary_file, 'rb')     
    mapping = pickle.load(dbfile)
    for i in range( len( long_cov_missing ) ):
        mapping[ sev_missing[ i ] ] = sev_mapping[ i ]
    dbfile.close()
    file = open( to_filename, "ab" )
    pickle.dump( mapping, file )
    file.close()


def SimplifyNetworkNameSev( network_file, to_file_name ):
    dbfile = open("VarRefs/sev_simp_var_dict.pickle", 'rb')
    mapping = pickle.load( dbfile )
    dbfile.close()
    SimplifyNetworkNames( network_file, to_file_name, mapping )

def SimplifyNetworkNameLongCov( network_file, to_file_name ):
    dbfile = open("VarRefs/sev_simp_var_dict.pickle", 'rb')
    mapping = pickle.load( dbfile )
    dbfile.close()
    SimplifyNetworkNames( "VarRefs/sev_simp_var_dict.pickle", to_file_name, mapping )